### PR TITLE
Implemented scrolling views

### PR DESCRIPTION
**Pull request by lukaciko**
Hi @sciutand 

I've got a question regarding the content below the tab bar; should the content be left/right scrollable, or can it be changed just by clicking on the tabs (with a fade out/fade in animation)?

The sample content is a bit boring now, I can change it for something more interesting.

Thanks

### CODE REVIEW

**Comment by sciutand** [comment]
Tabs clicking with fade in/out animation would be great.

You can pimp :candy:  the content if you want.

**Comment by sciutand** [comment]
Generally it looks good. One problem with the current implementation is that when scrolling down the table view stops at the top and I can only drag the tableview to reveal the cat again. Scrolling up and down should instead be seamless and fluid in both directions.

**Comment by lukaciko** [comment]
This might be an [an issue in support library](https://code.google.com/p/android/issues/detail?id=177729). I've reimplemented the scrolling with a different approach which doesn't use the app bar layout. There's still an issue where the tab bar might get incorrectly positioned which I'll try to fix tomorrow.

**Comment by sciutand** [comment]
Ok sounds good I'll wait for you final fix

**Pull request closed without merging**
