### PR TITLE
Init commit

### PR DESCRIPTION
**Pull request by micaklus**
Hi, I resolved #1

### CODE REVIEW

**Comment by sciutand** [comment]
@micaklus 
I found two issues with the current implementation. Can you please review

- When scrolling upward the top content is scrolled upward too. It should instead stay put and be covered by the header+tableview.
- When scrolling upward enough to hide the top content scrolling down stops with the tab header on top and a new scroll is required to reveal the summary again. The desired behaviour is for the header + tableviews to continue scrolling fluidly and reveal the top content as it goes down.
You can review the video for a better explanation than what I managed above :-)

**Comment by micaklus** [comment]
Hi,I fixed scroll problem and put static header, however top content still moves :)

**Comment by micaklus** [comment]
@sciutand 
Hi, I also fixed 
> When scrolling upward the top content is scrolled upward too. It should instead stay put and be covered by the header+tableview.

**Comment by sciutand** [comment]
@micaklus Thanks for the update

**Pull request closed without merging**
